apiVersion: v1
kind: Service
metadata:
  name: neg-demo-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    run: neg-demo-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9376